dayplanner/urls.py
from django.urls import path
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

from . import views


urlpatterns = [
    # home and daily tasks
    path('', views.HomeView.as_view(), name='home'),
    path('user', views.user, name='user'),
    path('introduction', views.introduction, name='introduction'),
    # archive
    path('archive', views.archive, name='archive'),
    path('archive/<int:year>/<int:month>/<int:day>', views.archive_get, name='archive_get'),
    # others
    path('copy_yesterday', views.copy_yesterday, name='copy_yesterday'),
    path('copy_task/<int:task_id>', views.copy_task, name='copy_task'),
    path('previous_<int:days>_days', views.previous_days, name='previous_days'),
    path('library', views.library, name='library'),
    path('projects', views.projects, name='projects'),
    path('projects/<int:category_id>', views.projects_get, name='projects_get'),
    path('deadlines', views.deadlines, name='deadlines'),
    # add
    path('add_category', views.add_category, name='add_category'),
    path('add_task', views.add_task, name='add_task'),
    path('add_subtask/<int:task_id>', views.add_subtask, name='add_subtask'),
    path('add_question', views.add_question, name='add_question'),
    path('add_answer/<int:question_id>', views.add_answer, name='add_answer'),
    path('add_motto', views.add_motto, name='add_motto'),
    # edit
    path('edit_category/', views.edit_category, name='edit_category'),
    path('edit_task/<int:task_id>', views.edit_task, name='edit_task'),
    path('edit_subtask/<int:subtask_id>', views.edit_subtask, name='edit_subtask'),
    path('add_counter/<int:subtask_id>', views.add_counter, name='add_counter'),
    path('edit_question/<int:question_id>', views.edit_question, name='edit_question'),
    path('edit_answer/<int:answer_id>', views.edit_answer, name='edit_answer'),
    path('edit_motto/', views.edit_motto, name='edit_motto'),
    # delete
    path('delete', views.delete, name='delete'),
    path('delete_category', views.delete_category, name='delete_category'),
    # finish
    path('task_finished/<int:task_id>', views.task_finished, name='task_finished'),
    path('task_not_finished/<int:task_id>', views.task_not_finished, name='task_not_finished'),
    path('subtask_finished/<int:subtask_id>', views.subtask_finished, name='subtask_finished'),
    path('subtask_not_finished/<int:subtask_id>', views.subtask_not_finished, name='subtask_not_finished'),
    # counter
    path('increment_counter/<int:counter_id>', views.increment_counter, name='increment_counter'),
    path('decrement_counter/<int:counter_id>', views.decrement_counter, name='decrement_counter'),
    # priority
    path('task_priority_increment/<int:task_id>', views.task_priority_increment, name='task_priority_increment'),
    path('task_priority_decrement/<int:task_id>', views.task_priority_decrement, name='task_priority_decrement'),
    path('subtask_priority_increment/<int:subtask_id>', views.subtask_priority_increment, name='subtask_priority_increment'),
    path('subtask_priority_decrement/<int:subtask_id>', views.subtask_priority_decrement, name='subtask_priority_decrement'),
    path('question_priority_increment/<int:question_id>', views.question_priority_increment, name='question_priority_increment'),
    path('question_priority_decrement/<int:question_id>', views.question_priority_decrement, name='question_priority_decrement'),
]

planner/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dayplanner.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
]

dayplanner/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

class Category(models.Model):
    """
    The category of task.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    project = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def task_due(self):
        return self.task_set.all().order_by('due')


class Task(models.Model):
    """
    Task to be completed.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    start = models.DateTimeField()
    due = models.DateTimeField()
    name = models.CharField(max_length=200)
    finished = models.BooleanField(default=False)
    finished_when = models.DateTimeField(auto_now=True)
    priority = models.IntegerField(default=1)

    def __str__(self):
        return self.name

    def increment(self):
        if self.priority < 20:
            self.priority += 1

    def decrement(self):
        if self.priority > 0:
            self.priority -= 1

    def subtask_priority(self):
        return self.subtask_set.all().order_by('priority')

    def clean(self):
        if hasattr(self, 'category') and hasattr(self, 'user'):
            if self.category.user != self.user:
                if self.start and self.due:
                    if self.start > self.due:
                        raise ValidationError([
                            ValidationError(_('You may only add Tasks to your own Categories/Projects.'), code='invalid'),
                            ValidationError(_('\'Due\' may not be older than \'Start\''), code='invalid'),
                        ])
                else:
                    raise ValidationError(_('You may only add Tasks to your own Categories/Projects.'), code='invalid')
        elif self.start and self.due:
            if self.start > self.due:
                raise ValidationError(_('\'Due\' may not be older than \'Start\''), code='invalid')


class SubTask(models.Model):
    """
    Smaller tasks that are part of full tasks.
    """
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    finished = models.BooleanField(default=False)
    finished_when = models.DateTimeField(auto_now=True)
    priority = models.IntegerField(default=1)

    def __str__(self):
        return self.name

    def increment(self):
        if self.priority < 20:
            self.priority += 1

    def decrement(self):
        if self.priority > 0:
            self.priority -= 1


class Counter(models.Model):
    """
    attached object incrementing for tasks
    """
    subtask = models.ForeignKey(SubTask, on_delete=models.CASCADE)
    count = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return str(self.count)

    def increment(self):
        if self.count < 301:
            self.count += 1

    def decrement(self):
        if self.count > 0:
            self.count -= 1


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    priority = models.IntegerField(default=1)

    def __str__(self):
        return self.question

    def increment(self):
        if self.priority < 20:
            self.priority += 1

    def decrement(self):
        if self.priority > 0:
            self.priority -= 1


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.answer


class Motto(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    motto = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)

    class Meta():
        get_latest_by = "date"

    def __str__(self):
        return self.motto

dayplanner/forms.py
from django import forms
from .models import Category, Task, SubTask, Question, Answer, Motto


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['user', 'name', 'project']


class TaskForm(forms.ModelForm):
    start = forms.DateTimeField(input_formats=['%Y-%m-%dT%H:%M'])
    due = forms.DateTimeField(input_formats=['%Y-%m-%dT%H:%M'])

    class Meta:
        model = Task
        fields = ['user', 'category', 'start', 'due', 'name', 'priority']
    
    def clean(self):
        super().clean()
        start = self.cleaned_data.get("start")
        due = self.cleaned_data.get("due")
        if start and due:
            if start > due:
                self.add_error('due', ' may not be older than \'Start\'')
        category = self.cleaned_data.get("category")
        if category.user != self.cleaned_data.get("user"):
            self.add_error('category', ' You may only add Tasks to your own Categories/Projects.')



class SubTaskForm(forms.ModelForm):
    class Meta:
        model = SubTask
        fields = ['task', 'name', 'priority']


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['user', 'question', 'priority']


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['question', 'answer']


class MottoForm(forms.ModelForm):
    class Meta:
        model = Motto
        fields = ['user', 'motto']


class DateForm(forms.Form):
    date = forms.DateField(label='Enter Date (YYYY-MM-DD)')

dayplanner/templates/archive.html
<!-- archive -->
{% extends 'base.html' %}
{% block title %}ARCHIVE{% endblock %}
{% block content %}
{% if date %}
<h2 class="center">{{ date|date:"M. j, Y" }}</h2>
<h2 class="center">{{ date|date:"l" }}</h2>
{% else %}
<h2 class="center">{% now "M. j, Y P" %}</h2>
<h2 class="center">{% now "l" %}</h2>
{% endif %}
<h1 class="underline">Archive</h1>
<nav>
    <a href="{% url 'add_task' %}">add task</a>
</nav>
<br>
<div>
<form action="{% url 'archive' %}" method="POST">
  {% csrf_token %}
  <table>
    <tr>
      <td colspan="2">
        <label for="date">Enter Date:</label>
      </td>
    </tr>
    <tr>
      <td>
        {% if date %}
          <input type="number" name="month" min="1" max="12" value="{{ date.month }}" placeholder="MM">
          <input type="number" name="day" min="1" max="31" value="{{ date.day }}" placeholder="DD">
          <input type="number" name="year" min="2018" max="2030" value="{{ date.year }}" placeholder="YYYY">
        {% else %}
          <input type="date" name="date" aria-label="Date">
        {% endif %}
      </td>
      <td>
        <input type="submit" value="submit" aria-label="Submit" class="button">
      </td>
    </tr>
  </table>
</form>
</div>
<br>
<table>
  {% if tasks %}
      <tr>
        <th>Task</th>
        <th>Category</th>
        <th>Due/Done</th>
        <th>Edit Delete Add</th>
      </tr>
    {% for task in tasks %}
      <tr>
        <td>{% if task.finished %}
                <input type="checkbox" checked disabled>
                <a href="{% url 'task_not_finished' task.id %}">
                  {% if task.priority > 0 %}{{ task.priority }}) {% endif %}{{ task }}
                </a>
            {% else %}
                <input type="checkbox" disabled>     
                <a href="{% url 'task_finished' task.id %}">
                  {% if task.priority > 0 %}{{ task.priority }}) {% endif %}{{ task }}
                </a>
            {% endif %}
        </td>
        <td>
          {{ task.category }}
        </td>
        <td>{% if task.finished %}
              Done:{{ task.finished_when|date:"m-d-y" }}
            {% else %}
              Due: {{ task.due|date:"m-d-y"}}
            {% endif %}
        </td>
        <td>
            <a href="{% url 'edit_task' task.id %}"> +</a>
            <form class="inline" method="POST" action="{% url 'delete' %}">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ task.id }}">
                <input type="hidden" name="object_type" value="task">
                <button class="delete" type="submit" aria-label="Submit">X</button>
            </form>
            <a href="{% url 'add_subtask' task.id %}"> #</a>
        </td>
    </tr>
        {% if task.subtask_set.all %}
            {% for subtask in task.subtask_priority %}
            <tr>
                <td class="subtask">{% if subtask.finished == True %}
                        <div class="black">_</div>
                        <input type="checkbox" checked disabled>
                        <a href="{% url 'subtask_not_finished' subtask.id %}">
                          {% if subtask.priority > 0 %}{{ subtask.priority }}) {% endif %}{{ subtask }}
                        </a>
                    {% else %}
                        <div class="black">_</div>
                        <input type="checkbox" disabled>
                        <a href="{% url 'subtask_finished' subtask.id %}">
                          {% if subtask.priority > 0 %}{{ subtask.priority }}) {% endif %}{{ subtask }}
                        </a>
                    {% endif %}
                </td>
                <td class="subtask">
                  {% if subtask.counter_set.all %}
                    {% for counter in subtask.counter_set.all %}
                      {{ counter }}
                      <a href="{% url 'increment_counter' counter.id %}"> +</a>
                      <a href="{% url 'decrement_counter' counter.id %}"> -</a>
                      <form class="inline" method="POST" action="{% url 'delete' %}">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ counter.id }}">
                        <input type="hidden" name="object_type" value="counter">
                        <button class="delete" type="submit" aria-label="Submit">X</button>
                      </form>
                    {% endfor %}
                  {% endif %}
                </td>
                <td class="subtask"></td>
                <td class="subtask">
                    <a href="{% url 'edit_subtask' subtask.id %}"> +</a>
                    <form class="inline" method="POST" action="{% url 'delete' %}">
                      {% csrf_token %}
                      <input type="hidden" name="id" value="{{ subtask.id }}">
                      <input type="hidden" name="object_type" value="subtask">
                      <button class="delete" type="submit" aria-label="Submit">X</button>
                    </form>
                    {% if not subtask.counter_set.all %}
                      <a href="{% url 'add_counter' subtask.id %}"> #</a>
                    {% endif %}
                </td>
            </tr>        
            {% endfor %}
        {% endif %}
    </tr>
  {% endfor %}
</table>
{% else %}
  <p>No tasks are available.</p>
{% endif %}
{% endblock %}

dayplanner/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS -->
    {% load static %}
    <link rel="shortcut icon" href="{% static 'dayplanner/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'dayplanner/style.css' %}">
    <title>{% block title %}base title{% endblock %}</title>
  </head>
  <body>
    <nav title="navigation">
      <a href="{% url 'home' %}">home</a> |
      <a href="{% url 'introduction' %}">introduction</a> |
      <a href="{% url 'projects' %}">projects</a> |
      <a href="{% url 'deadlines' %}">deadlines</a> |
      <a href="{% url 'previous_days' 7 %}">previous days</a> |
      <a href="{% url 'library' %}">library</a> |
      <a href="{% url 'archive' %}">archive</a> |
      {% if user.is_authenticated %}
        <a href="{% url 'user' %}">user: {{ user }}</a>
        <a href="{% url 'logout' %}?next={{request.path}}">[log out]</a>
      {% else %}
        <a href="{% url 'login' %}?next={{request.path}}">[login]</a> |
        <a href="{% url 'django_registration_register' %}">[register]</a>
      {% endif %}
    </nav>
    <br>
    {% if messages %}
      <ul class="no_padding">
      {% for message in messages %}
        <li>{{ message.tags.capitalize }}: {{ message }}</li>
      {% endfor %}
    {% else %}
        <li class="black">Info: No messages.</li>
      </ul>
    {% endif %}
    {% block content %}
    {% endblock %}
    </body>
</html>

dayplanner/templates/delete_category.html
<!--delete category -->
{% extends 'base.html' %}
{% block title %}DELETE CATEGORY/PROJECT{% endblock %}
{% block content %}
<h1 class="underline">Delete Category or Project</h1>
<nav>
	<a href="{% url 'add_category' %}">add category or project</a> |
	<a href="{% url 'edit_category' %}">edit category or project</a> |
	<a href="{% url 'add_task' %}">add task</a>
</nav>
<br>
	<form method="POST" action="{% url 'delete' %}">

        {% csrf_token %}
        <input type="hidden" name="object_type" value="category">
        <table>
		  <tr>
		    <td><select class="id" name="id" aria-label="Category">
					{% if categories %}
						{% for category in categories %}
						<option value="{{ category.id }}">{{ category }}</option>
						{% endfor %}
				{% endif %}
				</select></td>
		    <td><button class="button" type="submit" aria-label="Submit">Delete Category/Project</button></td>
		</tr>
		</table>
		
	</form>

{% endblock %}

dayplanner/templates/home.html
<!-- home -->
{% extends 'base.html' %}
{% block title %}HOME{% endblock %}
{% block content %}
<div class='center'>
<!-- motto -->
<p>
  {% if motto %}
  <a href="{% url 'edit_motto' %}">{{ motto }}</a>
{% else %}
  <a href="{% url 'add_motto' %}">add motto</a>
{% endif %}
</p>
<!-- question -->
{% if questions %}
  {% for q in questions %}
    <a href="{% url 'add_answer' q.id %}">{{ q }} </a>
    <a href="{% url 'edit_question' q.id %}"> +</a>
    <form class="inline" method="POST" action="{% url 'delete' %}">
      {% csrf_token %}
      <input type="hidden" name="id" value="{{ q.id }}">
      <input type="hidden" name="object_type" value="question">
      <button class="delete" type="submit" aria-label="Submit">X</button>
    </form>
    <p></p>
    {% if q.answer_set.all %}
      {% for answer in q.answer_set.all %}
        <p class='inline'>{{ answer }} </p>
        <a href="{% url 'edit_answer' answer.id %}"> +</a>
        <form class="inline" method="POST" action="{% url 'delete' %}">
          {% csrf_token %}
          <input type="hidden" name="id" value="{{ answer.id }}">
          <input type="hidden" name="object_type" value="answer">
          <button class="delete" type="submit" aria-label="Submit">X</button>
        </form>
      {% endfor %}
    {% else %}
    <a href="{% url 'add_answer' q.id %}">What is your resolution to this question?</a>
    {% endif %}
  {% endfor %}
{% else %}
  <a href="{% url 'add_question' %}">What question needs resolution today?</a>
{% endif %}
</div>
<h1 class="underline">Today's Tasks</h1>
<nav>
  <p class="inline">{% now 'D, M jS, P' %}</p> |
  <a href="{% url 'add_task' %}">add task</a> |
  <a href="{% url 'copy_yesterday' %}">copy yesterday</a>
</nav>
<br>
<table>
{% if tasks %}
    <tr>
      <th>Task</th>
      <th>Category</th>
      <th>Due/Done</th>
      <th>Edit Delete Add</th>
    </tr>
  {% for task in tasks %}
    <tr>
      <td>{% if task.finished %}
              <input type="checkbox" checked disabled>
              <a href="{% url 'task_not_finished' task.id %}">
                {% if task.priority > 0 %}{{ task.priority }}) {% endif %}{{ task }}
              </a>
          {% else %}
              <input type="checkbox" disabled>     
              <a href="{% url 'task_finished' task.id %}">
                {% if task.priority > 0 %}{{ task.priority }}) {% endif %}{{ task }}
              </a>
          {% endif %}
      </td>
      <td>
        {{ task.category }}
      </td>
      <td>{% if task.finished %}
            Done:{{ task.finished_when|date:"m-d-y" }}
          {% else %}
            Due: {{ task.due|date:"m-d-y"}}
          {% endif %}
      </td>
      <td>
          <a href="{% url 'edit_task' task.id %}"> +</a>
          <form class="inline" method="POST" action="{% url 'delete' %}">
              {% csrf_token %}
              <input type="hidden" name="id" value="{{ task.id }}">
              <input type="hidden" name="object_type" value="task">
              <button class="delete" type="submit" aria-label="Submit">X</button>
          </form>
          <a href="{% url 'add_subtask' task.id %}"> #</a>
      </td>
  </tr>
      {% if task.subtask_set.all %}
          {% for subtask in task.subtask_priority %}
          <tr>
              <td class="subtask">{% if subtask.finished == True %}
                      <div class="black">_</div>
                      <input type="checkbox" checked disabled>
                      <a href="{% url 'subtask_not_finished' subtask.id %}">
                        {% if subtask.priority > 0 %}{{ subtask.priority }}) {% endif %}{{ subtask }}
                      </a>
                  {% else %}
                      <div class="black">_</div>
                      <input type="checkbox" disabled>
                      <a href="{% url 'subtask_finished' subtask.id %}">
                        {% if subtask.priority > 0 %}{{ subtask.priority }}) {% endif %}{{ subtask }}
                      </a>
                  {% endif %}
              </td>
              <td class="subtask">
                {% if subtask.counter_set.all %}
                  {% for counter in subtask.counter_set.all %}
                    {{ counter }}
                    <a href="{% url 'increment_counter' counter.id %}"> +</a>
                    <a href="{% url 'decrement_counter' counter.id %}"> -</a>
                    <form class="inline" method="POST" action="{% url 'delete' %}">
                      {% csrf_token %}
                      <input type="hidden" name="id" value="{{ counter.id }}">
                      <input type="hidden" name="object_type" value="counter">
                      <button class="delete" type="submit" aria-label="Submit">X</button>
                    </form>
                  {% endfor %}
                {% endif %}
              </td>
              <td class="subtask"></td>
              <td class="subtask">
                  <a href="{% url 'edit_subtask' subtask.id %}"> +</a>
                  <form class="inline" method="POST" action="{% url 'delete' %}">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{ subtask.id }}">
                    <input type="hidden" name="object_type" value="subtask">
                    <button class="delete" type="submit" aria-label="Submit">X</button>
                  </form>
                  {% if not subtask.counter_set.all %}
                    <a href="{% url 'add_counter' subtask.id %}"> #</a>
                  {% endif %}
              </td>
          </tr>        
          {% endfor %}
      {% endif %}
  </tr>
{% endfor %}
{% endif %}
</table>
{% endblock %}

dayplanner/templates/previous_days.html
<!-- previous days -->
{% extends 'base.html' %}
{% block title %}PREVIOUS {{ days }} DAYS{% endblock %}
{% block content %}
<h1 class="underline">Previous {{ days }} Days</h1>
<nav>
  select days: 
  <a href="{% url 'previous_days' 7 %}">[seven]</a>
  <a href="{% url 'previous_days' 14 %}">[fourteen]</a>
  <a href="{% url 'previous_days' 30 %}">[thirty]</a>
  <a href="{% url 'previous_days' 100 %}">[one-hundred]</a>
  <a href="{% url 'previous_days' 365 %}">[365]</a>
</nav>
<br>
<table width="40%">
  <tr>
      <th>Day</th>
      <th>Archive</th>
  </tr>
  {% if data %}
  {% for day, date in data.items %}
  <tr>
    <td>{{ date|date:"l" }}</td>
    <td><a href="{% url 'archive_get' date.year date.month date.day %}">{{ date|date:"F jS" }}</a></td>
  </tr>
  {% endfor %}
  {% endif %}
</table>
{% endblock %}

dayplanner/templates/projects.html
<!--PROJECTS-->
{% extends 'base.html' %}
{% block title %}PROJECTS{% endblock %}
{% block content %}
<h1 class="underline">Projects</h1>
<nav>
    <a href="{% url 'add_category' %}">add project</a> |
    <a href="{% url 'delete_category' %}">delete project</a> |
    <a href="{% url 'add_task' %}">add task</a>
</nav>
<br>
	<form method="POST" action="{% url 'projects' %}">
		{% csrf_token %}
		<table>
		    <tr>
		        <td><select name="category_id" required>
                    {% if project %}
                        <option value="{{ project.id }}" selected>{{ project }}</option>
                    {% else %}
                        <option value="no_choice" selected hidden>Select Project</option>
                    {% endif %}
					{% if categories %}
						{% for category in categories %}
                            {% if category != project %}
						        <option value="{{ category.id }}">{{ category }}</option>
					        {% endif %}
						{% endfor %}
				    {% endif %}
				</select></td>
		    <td><button class="button" type="submit">Select Project</button></td>
		</tr>
		</table>
    </form>
{% if project %}
<table>
<h1 class="center">{{ project }}</h1>
    <tr>
        <th>Task</th>
        <th>Due/Done</th>
        <th>Edit Delete Add</th>
    </tr>
{% for task in project.task_due %}
    <tr>
        <td>{% if task.finished %}
                <input type="checkbox" class="finished" checked disabled>
                <a href="{% url 'task_not_finished' task.id %}">
                    {% if task.priority > 0 %}{{ task.priority }}) {% endif %}{{ task }}
                </a>
            {% else %}
                <input type="checkbox" class="finished" disabled>     
                <a href="{% url 'task_finished' task.id %}">
                    {% if task.priority > 0 %}{{ task.priority }}) {% endif %}{{ task }}
                </a>
            {% endif %}
        </td>
        <td>{% if task.finished %}
                Done:{{ task.finished_when|date:"m-d-y"  }}
            {% else %}
                Due: {{ task.due|date:"m-d-y"}}
            {% endif %}
        </td>
        <td>
            <a href="{% url 'edit_task' task.id %}"> +</a>
            <form class="inline" method="POST" action="{% url 'delete' %}">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ task.id }}">
                <input type="hidden" name="object_type" value="task">
                <button class="delete" type="submit" aria-label="Submit">X</button>
            </form>
            <a href="{% url 'add_subtask' task.id %}"> #</a>
        </td>
    </tr>
        {% if task.subtask_set.all %}
            {% for subtask in task.subtask_priority %}
            <tr>
                <td class="subtask">{% if subtask.finished == True %}
                        <input type="checkbox" class="finished" checked disabled>
                        <a href="{% url 'subtask_not_finished' subtask.id %}">
                            <div class="black">___</div>{% if subtask.priority > 0 %}{{ subtask.priority }}) {% endif %}{{ subtask }}
                        </a>
                    {% else %}
                        <input type="checkbox" class="finished" disabled>
                        <a href="{% url 'subtask_finished' subtask.id %}">
                            <div class="black">___</div>{% if subtask.priority > 0 %}{{ subtask.priority }}) {% endif %}{{ subtask }}
                        </a>
                    {% endif %}
                </td>
                <td class="subtask">
                    {% if subtask.counter_set.all %}
                        {% for counter in subtask.counter_set.all %}
                            {{ counter }}
                            <a href="{% url 'increment_counter' counter.id %}">+</a>
                            <a href="{% url 'decrement_counter' counter.id %}"> -</a>
                            <form class="inline" method="POST" action="{% url 'delete' %}">
                                {% csrf_token %}
                                <input type="hidden" name="id" value="{{ counter.id }}">
                                <input type="hidden" name="object_type" value="counter">
                                <button class="delete" type="submit" aria-label="Submit">X</button>
                            </form>
                        {% endfor %}
                    {% endif %}
                </td>
                <td class="subtask">
                    <a href="{% url 'edit_subtask' subtask.id %}"> +</a>
                    <form class="inline" method="POST" action="{% url 'delete' %}">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ subtask.id }}">
                        <input type="hidden" name="object_type" value="subtask">
                        <button class="delete" type="submit" aria-label="Submit">X</button>
                    </form>
                    {% if not subtask.counter_set.all %}
                        <a href="{% url 'add_counter' subtask.id %}"> #</a>
                    {% endif %}
                </td>
            </tr>        
            {% endfor %}
        {% endif %}
    </tr>
{% endfor %}
{% endif %}
</table>
{% endblock %}

dayplanner/templates/user.html
<!-- user -->
{% extends 'base.html' %}
{% block title %}USER{% endblock %}
{% block content %}
{% if user %}
<h1 class="underline">{{ user }}</h1>
<ul class="no_padding">
  {% if user.email %}
    <li>Email:</li>
	<li>{{ user.email }}</li>
    <br>
  {% endif %}
  <li>Joined:</li>
  <li>{{ user.date_joined }}</li>
  <br>
  <li>Most Recent Login:</li>
  <li>{{ user.last_login }}</li>
</ul>
<p>(Note: Only you can see your user profile. To change your email, username, or password, email 'mattskov1@gmail.com'.)</p>
{% endif %}
{% endblock %}